batch:
  scans:
    - image_path: input_lacunae_scans/f0000593.aim
      output_dir: outputs/f0000593
    - image_path: input_lacunae_scans/f0000594.aim
      output_dir: outputs/f0000594

thresholding:
  method: peak
  manual_threshold: 0.0
  use_otsu: true

scan:
  intensity_unit: bmd

density_filter:
  include_edge_lacunae: false
  edge_width: 2
